- id: python_file_name_check
  name: Python File name check
  description: check that filenames comply with pep8.
  entry: check_names
  language: python
  types:
    - file
    - python
  pass_filenames: true
  verbose: false
  args:
    - "--ignore-test-files"
  stages:
    - commit
    - push
    - manual
