name: TOX testing

"on":
  push:
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    env:
      TOX_PARALLEL_NO_SPINNER: 1  # Removes logging spam
    steps:
      - name: Checkout and setup Pythons
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install tox and run tests
        run: |
          pip install tox
          tox --parallel
